// ...existing code...
using CarRental.Data;
using Microsoft.EntityFrameworkCore;
// ...existing code...

builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration["ConnectionStrings:DefaultConnection"]));
// ...existing code...
